//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> ( LoopAnnotation() )?
 * f1 -> "for"
 * f2 -> "("
 * f3 -> Identifier()
 * f4 -> "="
 * f5 -> Expression()
 * f6 -> ";"
 * f7 -> Expression()
 * f8 -> ";"
 * f9 -> Identifier()
 * f10 -> "="
 * f11 -> Expression()
 * f12 -> ")"
 * f13 -> Statement()
 */
public class ForStatement implements Node {
   public NodeOptional f0;
   public NodeToken f1;
   public NodeToken f2;
   public Identifier f3;
   public NodeToken f4;
   public Expression f5;
   public NodeToken f6;
   public Expression f7;
   public NodeToken f8;
   public Identifier f9;
   public NodeToken f10;
   public Expression f11;
   public NodeToken f12;
   public Statement f13;

   public ForStatement(NodeOptional n0, NodeToken n1, NodeToken n2, Identifier n3, NodeToken n4, Expression n5, NodeToken n6, Expression n7, NodeToken n8, Identifier n9, NodeToken n10, Expression n11, NodeToken n12, Statement n13) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
      f6 = n6;
      f7 = n7;
      f8 = n8;
      f9 = n9;
      f10 = n10;
      f11 = n11;
      f12 = n12;
      f13 = n13;
   }

   public ForStatement(NodeOptional n0, Identifier n1, Expression n2, Expression n3, Identifier n4, Expression n5, Statement n6) {
      f0 = n0;
      f1 = new NodeToken("for");
      f2 = new NodeToken("(");
      f3 = n1;
      f4 = new NodeToken("=");
      f5 = n2;
      f6 = new NodeToken(";");
      f7 = n3;
      f8 = new NodeToken(";");
      f9 = n4;
      f10 = new NodeToken("=");
      f11 = n5;
      f12 = new NodeToken(")");
      f13 = n6;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

