//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> <SCOMMENT1>
 * f1 -> <LOOPTILE>
 * f2 -> IntegerLiteral()
 * f3 -> IntegerLiteral()
 * f4 -> <SCOMMENT2>
 */
public class LoopTileAnn implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public IntegerLiteral f2;
   public IntegerLiteral f3;
   public NodeToken f4;

   public LoopTileAnn(NodeToken n0, NodeToken n1, IntegerLiteral n2, IntegerLiteral n3, NodeToken n4) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
   }

   public LoopTileAnn(IntegerLiteral n0, IntegerLiteral n1) {
      f0 = new NodeToken("/*");
      f1 = new NodeToken("LOOPTILE");
      f2 = n0;
      f3 = n1;
      f4 = new NodeToken("*/");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

